models:
  random_forest:
    class: RandomForestClassifier
    params:
      n_estimators: [100]
      max_depth: [null]
      max_features: ['sqrt']
      min_samples_split: [2]
      min_samples_leaf: [1]
      class_weight: ['balanced']
  svm:
    class: SVC
    params:
      kernel: ['rbf']
      C: [1]
      gamma: ['scale']
  xgb:
    class: XGBClassifier
    params:
      max_depth: [5]
      learning_rate: [0.1]
      n_estimators: [100]
