models:
  mlp:
    class: MLPClassifier
    params:
      hidden_layer_sizes: [[64, 32], [128, 64, 32]]
      activation: ['relu']
      solver: ['adam']
      alpha: [0.0001, 0.001]
      learning_rate: ['constant', 'adaptive']
      max_iter: [500]
      batch_size: ['auto']
      early_stopping: [True]
  xgb:
    class: XGBClassifier
    params:
      max_depth: [2, 5]
      learning_rate: [0.05, 0.1]
      n_estimators: [100, 500]
  lgb:
    class: LGBMClassifier
    params:
      max_depth: [2, 5]
      learning_rate: [0.05, 0.1]
      n_estimators: [100, 500]
  svm:
    class: SVC
    params:
      kernel: ['linear', 'rbf']
      C: [0.1, 1, 10, 100]
      gamma: ['scale', 'auto']
  random_forest:
    class: RandomForestClassifier
    params:
      n_estimators: [100, 500]
      max_depth: [null, 5]
      max_features: ['sqrt', 'log2']
      min_samples_split: [2, 5]
      min_samples_leaf: [1, 2]
      class_weight: [null, 'balanced']
